[workspace]
authors = ["Todor Gitchev <todor.gitchev@uzh.ch>"]
channels = ["bioconda", "conda-forge"]
name = "cfDNA-Flow"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
snakemake = ">=9.8.1,<10"
pandas = ">=2.3.1,<3"
pyaml = ">=25.7.0,<26"
samtools = ">=1.22.1,<2"
bedtools = ">=2.31.1,<3"
bwa = ">=0.7.19,<0.8"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.30,<2"
deeptools = ">=3.5.6,<4"
picard = ">=3.4.0,<4"
numpy = ">=2.0.1,<3"
scipy = ">=1.16.0,<2"
pytest = ">=8.4.1,<9"
pytest-flake8 = ">=1.3.0,<2"
pytest-cov = ">=6.2.1,<7"
pytest-order = ">=1.3.0,<2"
biopython = ">=1.85,<2"
fastparquet = ">=2024.11.0,<2025"
logomaker = ">=0.8,<0.9"
mpmath = ">=1.3.0,<2"
patsy = ">=1.0.1,<2"
scikit-learn = ">=1.7.1,<2"
scikit-bio = ">=0.7.0,<0.8"
seaborn = ">=0.13.2,<0.14"
numba = ">=0.61.2,<0.62"
umap-learn = ">=0.5.9.post2,<0.6"
# ray-core = "*"
#liquorice = "*"

[pypi-dependencies]
